### PR TITLE
change 'raise' to 'warn' on unkown keys so changes to clowder spec don't break parsing

### PR DESCRIPTION
**Pull request by lindgrenj6**
Recently the clowdapp schema changed to add a `metadata` key, which stopped all of the sources-api pods from starting since the library would raise on an unsupported key.

Rather than just swallowing the error I just had it `warn` to STDERR instead. This way we do get warnings if the parsing isn't set up (the schema hasn't been updated yet on their end), but the parsing will go through and allow the pods to start.

### CODE REVIEW

**Comment by mkanoor** [comment]
@hsong-rh Do we just need to regenerate the schema here?

**Comment by hsong-rh** [comment]
@mkanoor Yes, every time when a schema is changed, we need to regenerate the library.

**Comment by hsong-rh** [comment]
@lindgrenj6 The types.rb is the autogenerated output file, marked on the first line, you don't need to change it.
`# This file is automatically generated by bin/json_schema_ruby`

**Comment by lindgrenj6** [comment]
Ah ok - I did run `ruby bin/json_schema_ruby lib/clowder-common-ruby/schema.json  -o lib/clowder-common-ruby/types.rb` to re-generate. I can pull out those changes though if you'd like. 

All I did was edit the generator to insert `warn` instead of `raise`, since we probably don't want to raise on an unknown key anyway since we are the only ones doing that. The schema also hasn't been updated on the clowder side yet - we can regenerate once it gets updated though.

**Comment by lindgrenj6** [comment]
Ok wel the unit tests dont pass unless I re-generate...I'll just separate it into a second commit.

**Review by hsong-rh — APPROVED** [review]

**Comment by hsong-rh** [comment]
@lindgrenj6 Dont forget to publish a new gem version.

**Comment by lindgrenj6** [comment]
I don't have access to that gem - can you grant me access for it? Either that or I can PR in the github action that will auto-release when the `version.rb` file changes.

**Pull request merged**
